In [16]:
!pip install scikit-learn
import pandas as pd

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)

In [17]:
df = pd.read_csv("/content/spam.csv")

In [18]:
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [19]:
df.groupby('Category').describe()

         Message                                                            \
           count unique                                                top
Category
ham         4825   4516                             Sorry, I'll call later
spam         747    641  Please call our customer service representativ...


         freq
Category
ham        30
spam        4

In [20]:
df['spam'] = df['Category'].apply(lambda x: 1 if x == 'spam' else 0)

In [21]:
df.head()

  Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [22]:
from sklearn.model_selection import train_test_split
X = df['Message']
y = df['spam']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2)

In [23]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_count = v.fit_transform(X_train.values)
X_train_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [24]:
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB

In [25]:
model = MultinomialNB()
model.fit(X_train_count,y_train)

MultinomialNB()

In [26]:
print("Model features:", model.n_features_in_)
print("Vectorizer features:", len(v.get_feature_names_out()))

Model features: 7768
Vectorizer features: 7768

In [27]:
emails = [
    "Go until jurong point, crazy.. Available only in bugis n great world la e buffet...",
    "Ok lar... Joking wif u oni...",
    "Free entry in 2 a wkly comp to win FA Cup final tkts..."
]

email_count = v.transform(emails)
predictions = model.predict(email_count)

print(predictions)

[0 0 1]

In [33]:
X_test_count = v.transform(X_test)
model.fit(X_test_count,y_test)
model.score(X_test_count,y_test)

0.9883408071748879

In [30]:
model.score(X_train_count,y_train)

0.9937177473636976

In [49]:
from sklearn.pipeline import Pipeline
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])
clf.fit(X_train,y_train)
clf.score(X_test,y_test)
clf.score(X_train,y_train)

0.9937177473636976