In [ ]:
import pandas as pd
!pip install scikit-learn

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)

In [ ]:
df = pd.read_csv("/content/titanic_ne2w.csv")

In [ ]:
df.head()
df.columns

Index(['PassengerId', 'Name', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked', 'Survived'],
      dtype='object')

In [ ]:
df.drop(['Ticket', 'PassengerId'],
        axis='columns',
        inplace=True)

In [ ]:
X = df.drop('Survived', axis=1)
y = df['Survived']

In [ ]:
X.head()

   Pclass     Sex   Age  SibSp     Fare
0       3    male  22.0      1   7.2500
1       1  female  38.0      1  71.2833
2       3  female  26.0      0   7.9250
3       1  female  35.0      1  53.1000
4       3    male  35.0      0   8.0500

In [ ]:
dummies = pd.get_dummies(X['Sex'])

In [ ]:
X = pd.concat([X,dummies], axis = 'columns')

In [ ]:
X.drop('Sex', axis=1, inplace=True)

In [ ]:
X

     Pclass   Age  SibSp     Fare  female   male
0         3  22.0      1   7.2500   False   True
1         1  38.0      1  71.2833    True  False
2         3  26.0      0   7.9250    True  False
3         1  35.0      1  53.1000    True  False
4         3  35.0      0   8.0500   False   True
..      ...   ...    ...      ...     ...    ...
886       2  27.0      0  13.0000   False   True
887       1  19.0      0  30.0000    True  False
888       3   NaN      1  23.4500    True  False
889       1  26.0      0  30.0000   False   True
890       3  32.0      0   7.7500   False   True

[891 rows x 6 columns]

In [ ]:
X.isnull().any()

Pclass    False
Age        True
SibSp     False
Fare      False
female    False
male      False
dtype: bool

In [ ]:
X['Age'] =X['Age'].fillna(X['Age'].mean())

In [ ]:
X.isnull().any()

Pclass    False
Age       False
SibSp     False
Fare      False
female    False
male      False
dtype: bool

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [ ]:
model.fit(X_train,y_train)

GaussianNB()

In [ ]:
model.score(X_test,y_test)

0.7821229050279329